name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: Gemfile
    strategy:
      matrix:
        ruby:
        - '2.1'
        - '2.2'
        - '2.3'
        - '2.4'
        - '2.5'
        - '2.6'

    name: Ruby ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run tests
        run: |
          bundle exec rake
